# Generated by Django 3.1.1 on 2020-09-17 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='end',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='log',
            name='start',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='plan',
            name='end',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='plan',
            name='start',
            field=models.CharField(max_length=15),
        ),
    ]
